server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://plazoleta-db.c6dbmianpmse.us-east-1.rds.amazonaws.com/plazoleta
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
appDescription: "Microservicio plazoleta"
appVersion: "1.0.0"

