server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
appDescription: "Microservicio plazoleta"
appVersion: "1.0.0"

